// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ygkwckgoqnrrlmprqcjn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlna3dja2dvcW5ycmxtcHJxY2puIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMDk2NDcsImV4cCI6MjA2NTU4NTY0N30.JaXWUcis0pqmTVT7MuCXJXoRXPQaAEr-Ysjbb1zhW7Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);